openapi: "3.0"
info:
  title: Open Service Broker API
  version: v2.13
paths:
  v2/catalog:
    get:
      summary: get the service catalog
      tags:
        - Catalog
      operationId: catalog.get
      responses:
        '200':
          description: catalog response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalog'


  /v2/service_instances/{instance_id}:
    put:
      summary: provision a service instance
      tags:
        - ServiceInstances
      operationId: serviceInstance.provision
      responses:
        '200':
          summary: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceProvisioning'
        '201':
          summary: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceProvisioning'
        '202':
          summary: Accepted
        '400':
          summary: Bad Request
        '409':
          summary: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
        '422':
          summary: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'

    patch:
      summary: update a service instance
      tags:
        - ServiceInstances
      operationId: serviceInstance.update
      responses:
        '200': 
          summary: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
        '202': 
          summary: Accepted
        '400': 
          summary: Bad Request
        '422': 
          summary: Unprocessable entity

    delete:
      summary: deprovision a service instance
      tags:
        - ServiceInstances
      operationId: serviceInstance.deprovision
      responses:
        '200'
          summary: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
        '202'
          summary: Accepted
        '400'
          summary: Bad Request
        '410'
          summary: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
        '422'
          summary: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'


  v2/service_instances/{instance_id}/last_operation:
    get:
      summary: TODO
      tags:
        - ServiceInstances
        - Async
      operationId: serviceInstance.lastOperation.get
      responses:
        '200':
          summary: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceLastOperation'
        '400':
          summary: Bad Request
        '410':
          summary: Gone


  /v2/service_instances/{instance_id}/service_bindings/{binding_id}:
    put:
      summary: binding
      tags:
        - Bindings
      operationId: serviceBinding.binding
      responses:
        '200':
          summary: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBindingsBinding'
        '201':
          summary: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBindingsBinding'
        '400':
          summary: Bad Request
        '409':
          summary: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        '422':
          summary: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
    delete:
      summary: unbinding
      tags:
        - Bindings
      operationId: serviceBinding.unbinding
      responses:
        '200':
          summary: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'
        '400':
          summary: Bad Request
        '410':
          summary: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empty'

components:
  schemas:
    Catalog: TODO
    ServiceInstanceProvisioning: TODO
    ServiceInstanceLastOperation: TODO
    ServiceBindingsBinding: TODO
    Empty: TODO
    Errors: 
      properties:
        error:
          type: string
        description:
          type: string
security:
  todo
tags:
  todo
externalDocs:
  description: The offical OSB specification
  url: https://github.com/openservicebrokerapi/servicebroker/
