#
# todo: define $refs that link to nothing.
#

openapi: "3.0.0"
info:
  title: Open Service Broker API
  version: v2.13
paths:
  /v2/catalog:
    get:
      summary: get the service catalog
      tags:
        - Catalog
      operationId: catalog.get
      parameters:
        - $ref: '#/components/headers/X-Broker-API-Version'
      responses:
        '200':
          description: catalog response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalog'
#
#
  /v2/service_instances/{instance_id}:
    put:
      summary: provision a service instance
      tags:
        - ServiceInstances
      operationId: serviceInstance.provision
      parameters:
        - $ref: '#/components/headers/X-Broker-API-Version'
        - $ref: '#/components/headers/X-Broker-API-Originating-Identity'
        - name: instance_id
          in: path
          description: instance id of instance to provision
          required: true
          schema:
            type: string
        - name: accepts_incomplete
          in: query
          description: asynchronous operations supported
          schema:
            type: boolean
      requestBody:
        description: parameters for the requested service instance provision
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceInstanceProvisionRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceProvision'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceProvision'
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'

    patch:
      summary: update a service instance
      tags:
        - ServiceInstances
      operationId: serviceInstance.update
      parameters:
        - $ref: '#/components/headers/X-Broker-API-Version'
        - $ref: '#/components/headers/X-Broker-API-Originating-Identity'
        - name: instance_id
          in: path
          description: instance id of instance to update
          required: true
          schema:
            type: string
        - name: accepts_incomplete
          in: query
          description: asynchronous operations supported
          schema:
            type: boolean
      requestBody:
        description: parameters for the requested service instance update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceInstanceUpdateRequest'
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        '202': 
          description: Accepted
        '400': 
          description: Bad Request
        '422': 
          description: Unprocessable entity

    delete:
      summary: deprovision a service instance
      tags:
        - ServiceInstances
      operationId: serviceInstance.deprovision
      parameters:
        - $ref: '#/components/headers/X-Broker-API-Version'
        - $ref: '#/components/headers/X-Broker-API-Originating-Identity'
        - name: instance_id
          in: path
          description: id of instance being deleted
          required: true
          schema:
            type: string
        - name: service_id
          in: query
          description: id of the service associated with the instance being deleted
          schema:
            type: string
        - name: plan_id
          in: query
          description: id of the plan associated with the instance being deleted
          schema:
            type: string
        - name: accepts_incomplete
          in: query
          description: asynchronous deprovision supported
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '410':
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'


  /v2/service_instances/{instance_id}/last_operation:
    get:
      summary: last requested operation state
      tags:
        - ServiceInstances
      operationId: serviceInstance.lastOperation.get
      parameters:
        - $ref: '#/components/headers/X-Broker-API-Version'
        - name: instance_id
          in: path
          description: instance id of instance to find last operation applied to it
          required: true
          schema:
            type: string
        - name: service_id
          in: query
          description: id of the service being used
          schema:
            type: string
        - name: plan_id
          in: query
          description: id of the plan being used
          schema:
            type: string
        - name: operation
          in: query
          description: a provided identifier for the operation
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInstanceLastOperation'
        '400':
          description: Bad Request
        '410':
          description: Gone


  /v2/service_instances/{instance_id}/service_bindings/{binding_id}:
    put:
      summary: generation of a service binding
      tags:
        - ServiceBindings
      operationId: serviceBinding.binding
      parameters:
        - $ref: '#/components/headers/X-Broker-API-Version'
        - $ref: '#/components/headers/X-Broker-API-Originating-Identity'
        - name: instance_id
          in: path
          description: instance id being bound
          required: true
          schema:
            type: string
        - name: binding_id
          in: path
          description: binding id being bound
          required: true
          schema:
            type: string
      requestBody:
        description: parameters for the requested service binding
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceBindingRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBinding'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceBinding'
        '400':
          description: Bad Request
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
    delete:
      summary: deprovision of a service binding
      tags:
        - ServiceBindings
      operationId: serviceBinding.unbinding
      parameters:
        - $ref: '#/components/headers/X-Broker-API-Version'
        - $ref: '#/components/headers/X-Broker-API-Originating-Identity'
        - name: instance_id
          in: path
          description: id of the instance associated with the binding being deleted
          required: true
          schema:
            type: string
        - name: binding_id
          in: path
          description: id of the binding being deleted
          required: true
          schema:
            type: string
        - name: service_id
          in: query
          description: id of the service associated with the binding being deleted
          schema:
            type: string
        - name: plan_id
          in: query
          description: id of the plan associated with the binding being deleted
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        '400':
          description: Bad Request
        '410':
          description: Gone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'


components:
  schemas:
    Catalog:
      type: object
      properties:
        services:
          type: array
          items:
            $ref: '#/components/schemas/Service'

    Service:
      required:
        - name
        - id
        - description
        - bindable
        - plans
      properties:
        name:
          type: string
        id:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        requires:
          type: array
          items:
            type: string
        bindable:
          type: boolean
        metadata:
          $ref: '#/components/schemas/Object'
        dashboard_client:
          $ref: '#/components/schemas/DashboardClient'
        plan_updateable:
          type: boolean
        plans:
          type: array
          items:
            $ref: '#/components/schemas/Plan'

    DashboardClient:
      properties:
        id:
            type: string
        secret:
            type: string
        redirect_uri:
            type: string

    Plan:
      required:
        - id
        - name
        - description
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        metadata:
          $ref: '#/components/schemas/Object'
        free:
          type: boolean
          default: true
        bindable:
          type: boolean
        schemas:
          $ref: '#/components/schemas/SchemasObject'

    SchemasObject:
      properties:
        service_instance:
          $ref: '#/components/schemas/ServiceInstanceSchemaObject'
        service_binding:
          $ref: '#/components/schemas/ServiceBindingSchemaObject'

    ServiceInstanceSchemaObject:
      properties:
        create:
          $ref: '#/components/schemas/JSONSchemaObject'
        update:
          $ref: '#/components/schemas/JSONSchemaObject'

    ServiceBindingSchemaObject:
      properties:
        create:
          $ref: '#/components/schemas/JSONSchemaObject'

    JSONSchemaObject:
      type: object

    ServiceInstanceProvisionRequest:
      required:
        - service_id
        - plan_id
        - organization_guid
        - space_guid
      properties:
        service_id:
          type: string
        plan_id:
          type: string
        context:
          $ref: '#/components/schemas/Object'
        organization_guid:
          type: string
          deprecated: true
        space_guid:
          type: string
          deprecated: true
        parameters:
          $ref: '#/components/schemas/Object'

    ServiceInstanceProvision:
      properties:
        dashboard_url:
          type: string
        operation:
          type: string # could be a link object to last operation

    ServiceInstanceUpdateRequest:
      properties:
        todo:
          type: boolean

    ServiceInstanceLastOperation:
      required:
        - state
      properties:
        state:
          type: string
          enum:
            - in progress
            - succeeded
            - failed
        description:
          type: string

    ServiceBindingRequest:
      properties:
        todo:
          type: boolean

    ServiceBinding:
      properties:
        todo:
          type: boolean

    Object:
      type: object

    Errors: 
      properties:
        error:
          type: string
        description:
          type: string
          
  headers:
    X-Broker-API-Version:
      description: version number of the Service Broker API that the Platform will use
      required: true
      schema:
        type: string
      default: '2.13'
    X-Broker-API-Originating-Identity:
      description: identity of the user that initiated the request from the Platform
      schema:
        type: string

#security:
#  todo
#tags:
#  todo
externalDocs:
  description: The offical OSB specification
  url: https://github.com/openservicebrokerapi/servicebroker/
